### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by greghao** [dceoy/docker-nginx-autoindex#1]
hello, would it be possible to request an arm64 build of this docker? thank you!

**Comment by dceoy** [comment]
This issue was fixed.
Currently, the images for both ARM and x86 are available.
https://github.com/dceoy/docker-nginx-autoindex/blob/a1bdb6acd5afeb5bfb7cdc4618e41dc7f723c51c/.github/workflows/ci.yml#L42
